# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/NSData+MulleHoedown.m
src/NSString+MulleHoedown.m
src/hoedown/autolink.c
src/hoedown/buffer.c
src/hoedown/document.c
src/hoedown/escape.c
src/hoedown/html_blocks.c
src/hoedown/html.c
src/hoedown/html_smartypants.c
src/hoedown/stack.c
src/hoedown/version.c
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleHoedown.m
)
