#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleHoedown.m
src/NSData+MulleHoedown.m
src/NSString+MulleHoedown.m
src/hoedown/autolink.c
src/hoedown/buffer.c
src/hoedown/document.c
src/hoedown/escape.c
src/hoedown/html_blocks.c
src/hoedown/html.c
src/hoedown/html_smartypants.c
src/hoedown/stack.c
src/hoedown/version.c
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleHoedown.m
)
