      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCLockFoundation) },      // 47a9beb6;MulleObjCLoader;86a97828;MulleObjCLockFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleHoedown), MULLE_OBJC_NO_CATEGORYID },      // 706a0068;MulleHoedown;;
      { @selector( NSData), @selector( MulleHoedown) },      // 8fce7861;NSData;706a0068;MulleHoedown
      { @selector( NSString), @selector( MulleHoedown) },      // 1994a171;NSString;706a0068;MulleHoedown
