      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleHoedown), MULLE_OBJC_NO_CATEGORYID },      // 706a0068;MulleHoedown;;
      { @selector( NSData), @selector( MulleHoedown) },      // 8fce7861;NSData;706a0068;MulleHoedown
      { @selector( NSString), @selector( MulleHoedown) },      // 1994a171;NSString;706a0068;MulleHoedown
