#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/hoedown
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_HEADERS
src/MulleHoedown.h
src/MulleObjCLoader+MulleHoedown.h
src/NSData+MulleHoedown.h
src/NSString+MulleHoedown.h
src/hoedown/autolink.h
src/hoedown/buffer.h
src/hoedown/document.h
src/hoedown/escape.h
src/hoedown/html.h
src/hoedown/stack.h
src/hoedown/version.h
src/import.h
)

